#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-sprockets
Version  : 3.4.1
Release  : 9
URL      : https://rubygems.org/downloads/sprockets-3.4.1.gem
Source0  : https://rubygems.org/downloads/sprockets-3.4.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-sprockets-bin
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# Sprockets: Rack-based asset packaging
Sprockets is a Ruby library for compiling and serving web assets.
It features declarative dependency management for JavaScript and CSS
assets, as well as a powerful preprocessor pipeline that allows you to
write assets in languages like CoffeeScript, Sass and SCSS.

%package bin
Summary: bin components for the rubygem-sprockets package.
Group: Binaries

%description bin
bin components for the rubygem-sprockets package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n sprockets-3.4.1
gem spec %{SOURCE0} -l --ruby > rubygem-sprockets.gemspec

%build
gem build rubygem-sprockets.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
sprockets-3.4.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/sprockets-3.4.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/bin/sprockets
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/rake/sprocketstask.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/asset.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/autoload.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/autoload/closure.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/autoload/coffee_script.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/autoload/eco.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/autoload/ejs.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/autoload/sass.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/autoload/uglifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/autoload/yui.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/bower.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/bundle.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/cache/file_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/cache/memory_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/cache/null_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/cached_environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/closure_compressor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/coffee_script_processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/coffee_script_template.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/compressing.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/context.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/dependencies.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/digest_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/directive_processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/eco_processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/eco_template.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/ejs_processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/ejs_template.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/encoding_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/engines.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/erb_processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/erb_template.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/file_reader.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/http_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/jst_processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy_proc_processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/legacy_tilt_processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/loader.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/manifest.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/manifest_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/mime.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_dependency_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_digest_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/path_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/paths.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processing.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/processor_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/resolve.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_cache_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_compressor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_functions.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_importer.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_processor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/sass_template.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/server.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/transformers.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/uglifier_compressor.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/unloaded_asset.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/uri_tar.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/uri_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/sprockets-3.4.1/lib/sprockets/yui_compressor.rb
/usr/lib64/ruby/gems/2.3.0/specifications/sprockets-3.4.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/sprockets
